### ISSUE TITLE
Будут ли апдейты?

### ISSUE THREAD

**Issue by des1roer** [voskobovich/ManyToManyBehavior#11]
Вы думаете реализовали полный функционал?

**Comment by voskobovich** [comment]
О каких апдейтах речь?

**Comment by voskobovich** [comment]
Вопрос с подвохом или есть предложения?

**Comment by des1roer** [comment]
поддержка Postgres например

**Comment by voskobovich** [comment]
Конечно, в будущем мы планируем реализовать поддержку базы PostgreSQL.
Если вам нужен этот функционал срочно, можете поддержать проект финансово и мы реализуем его незамедлительно.
