### ISSUE TITLE
Как вывести в index и view данные связанных моделей?

### ISSUE THREAD

**Issue by des1roer** [voskobovich/ManyToManyBehavior#13]
Хочу в индексе в таблице в поле со связью многие-ко-многи вывести имена из свзяанной модели

**Comment by voskobovich** [comment]
В каком индексе? В какой таблице? Что за поле?
Перефразируйте свою задачу, приведите примеры, скажите что не получилось сделать после прочтения доки.

**Comment by des1roer** [comment]
в общем сделал. не знаю насколько это правильно. если можете поправьте 
примитивный пример
![screenshot_45](https://cloud.githubusercontent.com/assets/10970793/9927291/d45c4582-5d36-11e5-83af-06cc5c6cf0ee.png)
устанавливаю композером расширение.

    public function behaviors()
    {
        return [
            [
                'class' => \voskobovich\behaviors\ManyToManyBehavior::className(),
                'relations' => [
                    'perks_list' => 'perks',
                ],
            ],
        ];
    }

при выводе в unit/index 
gridview

                    [
                        'format' => 'raw',
                        'label' => 'lol',
                        'value' => function($data)
                        {
                            return $data->myperks;
                        },
                    ],
model

    public function getPerks()
    {
        return $this->hasMany(Perk::className(), ['id' => 'perk_id'])
                        ->viaTable('unit_has_perk', ['unit_id' => 'id']);
    }
    //
    public function getMyperks()
    {
        $perks = $this->perks;       
        for($i = 0; $i <= count($perks); $i++)
        {
          if (!empty($perks[$i]['name'])) $perk[] = Html::a($perks[$i]['name'], ['/person/perk/view',  'id' => $perks[$i]['id'],], ['class' => 'btn btn-link'])  ;
        }
        return ($perk)  ? implode($perk) : ''; 
    }

**Comment by voskobovich** [comment]
Работа со связями описана здесь http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#relational-data

Скажите что не работает, в чем проблема?

**Comment by des1roer** [comment]
все работает. думал красивее решение есть

**Comment by voskobovich** [comment]
Для советов есть форум.
В этом репо обсуждаются вопросы\пожелания\предложения по ManyToManyBehavior.
Пожалуйста, не засоряйте список тем.
