### ISSUE TITLE
Как использовать в DetailView

### ISSUE THREAD

**Issue by des1roer** [voskobovich/ManyToManyBehavior#19]
для index можно использовать 

                    [
                        'format' => 'raw',
                        'label' => 'lol',
                        'value' => function($data)
                        {
                            return $data->myperks;
                        },
                    ],

но при добавлении этого кода в DetailView получаю 

        Object of class Closure could not be converted to string

как изменить код? 

делаю по http://habrahabr.ru/post/244709/

**Comment by des1roer** [comment]
DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'format' => 'raw',
                'label' => 'lol',
                'value' => $model->myperks,
            ],

**Comment by voskobovich** [comment]
А разве 
```
DetailView::widget([
    'model' => $model,
    'attributes' => [
        [
            'format' => 'raw',
            'label' => 'lol',
            'value' => function($model) {
                    return $model->myperks;
            },
        ],
```
?
