### ISSUE TITLE
Check if related entry exists

### ISSUE THREAD

**Issue by thejahweh** [voskobovich/ManyToManyBehavior#9]
If the given ID not exists it tries to insert it anyway and does not check it. Maybe this could be done via a validator?

**Comment by beowulfenator** [comment]
Such validation should be performed in the model itself, the one you are attaching this behavior to. So, to continue the example given in the README:

    public function rules()
    {
        return [
            //...
            [['author_list'], 'each', 'rule' => [
                'exist',
                'targetClass' => Author::className(),
                'targetAttribute' => 'id'
            ]],
            //...
        ];
    }



Just keep in mind that such validation will make an SQL query for every id passed in the array. You're welcome to implement your own validator optimized for efficiency.
